project:
  type: book

website: 
  google-analytics: "G-5T7SZYQV79"
  
book:
  title: "R4PDE"

  chapters:
    - index.qmd
    - epidemic-data.qmd
    - temporal.qmd
    - spatial-gradients.qmd
    - spatial-patterns.qmd
    - references.qmd

bibliography: references.bib
csl: phytopathology.csl
format:
  html:
    toc: true
    toc-depth: 5
    theme: 
      light: flatly
   
  pdf:
    documentclass: scrreprt

editor: visual

