project:
  type: book

book:
  
  google-analytics: "G-5T7SZYQV79"
  title: "R4PDE"
  author: "Emerson M. Del Ponte"
  search: true
  repo-url: https://github.com/emdelponte/epidemiology-R
  cover-image: cover.png
  repo-actions: [edit, issue]
  page-footer: 
    border: false
    background: light
    left: "R for Plant Disease Epidemiology is written by Emerson Del Ponte"
    right:
      
      - icon: github
        href: "https://github.com/emdelponte/epidemiology-R"
       
  chapters:
    - index.qmd
    - author.qmd
    - intro.qmd
    - part: "Epidemic data"
      chapters:
        - data-terminology.qmd
        - data-type-distributions.qmd
        - data-accuracy.qmd
        - data-actual-severity.qmd
    - part: "Temporal analysis"
      chapters: 
        - temporal-dpc.qmd
        - temporal-models.qmd
        - temporal-fitting.qmd
        - temporal-simulation.qmd
    - part: "Spatial analysis"
      chapters:
        - spatial-gradients.qmd
        - spatial-models.qmd
        - spatial-fitting.qmd
        - spatial-patterns.qmd
        - spatial-tests.qmd
    - references.qmd


bibliography: references.bib

csl: phytopathology.csl
format:
  html:
    toc: true
    toc-depth: 5
    theme: 
      light: cosmo
   
  docx:
    toc: true
    number-sections: true
    highlight-style: github



