project:
  type: book

website: 
  google-analytics: "G-5T7SZYQV79"
  
book:
  title: "R4PDE"
  author: "Emerson M. Del Ponte"
  search: true
  repo-url: https://github.com/emdelponte/epidemiology-R
  cover-image: cover.png
  page-footer: 
    border: false
    background: light
    left: "Copyright 2022, Emerson Del Ponte"
    right:
      - icon: github
        href: "https://github.com/emdelponte/epidemiology-R"
      
  chapters:
    - index.qmd
    - epidemic-data.qmd
    - temporal.qmd
    - spatial-gradients.qmd
    - spatial-patterns.qmd
    - references.qmd

bibliography: references.bib
csl: phytopathology.csl
format:
  html:
    toc: true
    toc-depth: 5
    theme: 
      light: flatly
   
  pdf:
    documentclass: scrreprt

editor: visual

