project:
  type: book

book:
  title: "R4PDE"
  author: "Emerson M. Del Ponte"
  date: "4/22/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - temporal.qmd
    - spatial-gradients.qmd
    - spatial-patterns.qmd
    - references.qmd

bibliography: references.bib
csl: phytopathology.csl
format:
  html:
    theme: zephyr
  pdf:
    documentclass: scrreprt

editor: visual

