project:
  type: book

book:
  title: "R4PDE"

  chapters:
    - index.qmd
    - temporal.qmd
    - spatial-gradients.qmd
    - spatial-patterns.qmd
    - references.qmd

bibliography: references.bib
csl: phytopathology.csl
format:
  html:
    toc: true
    toc-depth: 5
    theme: 
      light: lumen
   
  pdf:
    documentclass: scrreprt

editor: visual

